spring.application.name=elesafe

spring.data.mongodb.uri=${MONGO_URI}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
server.port=${PORT:8080}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.example.jkr.elesafe
springdoc.pathsToMatch=/**
springdoc.swagger-ui.operationsSorter=method

# Timezone for rendering dates
spring.jackson.time-zone=UTC