spring.application.name=elesafe

#spring.data.mongodb.uri=mongodb+srv://waruna:123@cluster0.rzlyd9r.mongodb.net/elesafe_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://elesafe_user:1234@cluster0.8spzn2n.mongodb.net/elesafe_db?appName=Cluster0

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800000

server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.example.jkr.elesafe
springdoc.pathsToMatch=/**
springdoc.swagger-ui.operationsSorter=method